/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    occasions: Occasion;
    media: Media;
    testimonials: Testimonial;
    clients: Client;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'shop-page': ShopPage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'pre-order-page': PreOrderPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'shop-page': ShopPageSelect<false> | ShopPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'pre-order-page': PreOrderPageSelect<false> | PreOrderPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Everything that appears as a product card on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * The one-line description under the name on the product card. Keep it short.
   */
  blurb: string;
  /**
   * Which collection this belongs to.
   */
  category: string | Category;
  /**
   * Drives the Shop page occasion filter.
   */
  occasions: (string | Occasion)[];
  /**
   * Optional longer paragraph on the product page. Leave blank to use the blurb.
   */
  description?: string | null;
  /**
   * Main photo. If left empty the category cover photo is used instead.
   */
  image?: (string | null) | Media;
  /**
   * Extra photos shown as thumbnails on the product page.
   */
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Price in Rs. per unit. Leave empty to show "Price on WhatsApp" instead.
   */
  price?: number | null;
  /**
   * What one item is: box, piece, pair, set, cone, jar…
   */
  unit?: string | null;
  specs?: {
    material?: string | null;
    size?: string | null;
    finish?: string | null;
    moq?: string | null;
  };
  /**
   * Used in the page URL. Filled in automatically from the name — only change it before the page is shared anywhere.
   */
  slug: string;
  /**
   * Featured products appear in the Best sellers row on the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first on the site.
   */
  order?: number | null;
  /**
   * Old product URL id. Keeps links shared before the CMS working.
   */
  legacyId?: string | null;
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The collections shown in the header, footer and Shop by category grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Shown everywhere, e.g. "Tin Boxes".
   */
  name: string;
  /**
   * Used in the page URL. Filled in automatically from the name — only change it before the page is shared anywhere.
   */
  slug: string;
  /**
   * One-line subtitle under the name on category cards.
   */
  short: string;
  /**
   * The opening paragraph on the category page.
   */
  intro: string;
  /**
   * Category cover photo, used on cards, rails and the category page. The site shows a plain cream panel until one is set.
   */
  image?: (string | null) | Media;
  /**
   * Controls the price line on the category page header.
   */
  pricing: 'boxRange' | 'quote';
  /**
   * Lower numbers appear first on the site.
   */
  order?: number | null;
  /**
   * Shown on every product in this category unless the product overrides them.
   */
  specs: {
    material: string;
    size: string;
    finish: string;
    moq: string;
  };
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Every photo used on the site. Upload once here, then pick it on a product or category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the photo for screen readers and Google, e.g. "Green embroidered Mehndi handheld sign with gold Urdu calligraphy".
   */
  alt: string;
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryVersion?: number | null;
  cloudinaryFormat?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * Nikkah, Walima, Mehndi and friends — used for the shop filter and menus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: string;
  name: string;
  /**
   * Used in the page URL. Filled in automatically from the name — only change it before the page is shared anywhere.
   */
  slug: string;
  /**
   * Short explainer, e.g. "The marriage ceremony".
   */
  note: string;
  /**
   * Single emoji shown in the occasion circle.
   */
  emoji: string;
  /**
   * Lower numbers appear first on the site.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The "Kind words" cards at the bottom of the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  authorName: string;
  /**
   * Shown after the name, e.g. "Walima order".
   */
  context: string;
  rating?: number | null;
  /**
   * Lower numbers appear first on the site.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Names in the scrolling "Trusted by" strip and the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  name: string;
  /**
   * Optional. The strip currently shows names as text.
   */
  logo?: (string | null) | Media;
  /**
   * Lower numbers appear first on the site.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'occasions';
        value: string | Occasion;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  blurb?: T;
  category?: T;
  occasions?: T;
  description?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  price?: T;
  unit?: T;
  specs?:
    | T
    | {
        material?: T;
        size?: T;
        finish?: T;
        moq?: T;
      };
  slug?: T;
  featured?: T;
  order?: T;
  legacyId?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  short?: T;
  intro?: T;
  image?: T;
  pricing?: T;
  order?: T;
  specs?:
    | T
    | {
        material?: T;
        size?: T;
        finish?: T;
        moq?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  note?: T;
  emoji?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  cloudinaryPublicId?: T;
  cloudinaryVersion?: T;
  cloudinaryFormat?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  context?: T;
  rating?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, prices and the WhatsApp message wording used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  brandName: string;
  /**
   * The short paragraph in the footer.
   */
  tagline: string;
  /**
   * The dark strip above the header. Leave blank to hide it entirely.
   */
  announcementBar?: string | null;
  /**
   * Optional. Replaces the letter B circle in the header once uploaded.
   */
  logo?: (string | null) | Media;
  footerNote?: string | null;
  /**
   * International format, digits only, no + or spaces. e.g. 923079701492
   */
  whatsappNumber: string;
  /**
   * How the number is written on the page.
   */
  phoneDisplay: string;
  email: string;
  instagramUrl: string;
  instagramHandle: string;
  /**
   * Days of notice needed before an event. Sets the earliest pre-order date.
   */
  leadTimeDays: number;
  /**
   * Low end of the standard box price range, in Rs.
   */
  boxPriceMin: number;
  /**
   * High end of the standard box price range, in Rs.
   */
  boxPriceMax: number;
  /**
   * Shown instead of a price when a product has none.
   */
  quoteNote: string;
  waTemplates: {
    general: string;
    order: string;
    custom: string;
    /**
     * Uses {product} and {qty}.
     */
    product: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every block on the homepage, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    eyebrow: string;
    title: string;
    body: string;
    /**
     * Links to the Shop page.
     */
    primaryCta: string;
    secondaryCta: string;
    /**
     * The small grey lines under the hero buttons.
     */
    badges?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: string | Media;
    /**
     * The little floating card over the hero photo.
     */
    priceBadge?: {
      title?: string | null;
      sub?: string | null;
    };
  };
  clientsHeading: string;
  categoriesSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
    /**
     * Optional supporting line. Leave blank to hide.
     */
    sub?: string | null;
  };
  collectionsSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
    /**
     * Optional supporting line. Leave blank to hide.
     */
    sub?: string | null;
  };
  occasionsSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
    /**
     * Optional supporting line. Leave blank to hide.
     */
    sub?: string | null;
  };
  featuredSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
    /**
     * Optional supporting line. Leave blank to hide.
     */
    sub?: string | null;
  };
  /**
   * How many products to show in the Best sellers row.
   */
  featuredLimit?: number | null;
  howToOrderSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
    /**
     * Optional supporting line. Leave blank to hide.
     */
    sub?: string | null;
  };
  howToOrderSteps?:
    | {
        title: string;
        body: string;
        icon?: ('sparkles' | 'message' | 'truck' | 'palette' | 'clock') | null;
        id?: string | null;
      }[]
    | null;
  instagramSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
    /**
     * Optional supporting line. Leave blank to hide.
     */
    sub?: string | null;
  };
  /**
   * Six photos linking to your profile. Leave empty to fall back to category covers.
   */
  instagramImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  instagramCta?: string | null;
  testimonialsSection: {
    /**
     * Small uppercase line above the heading.
     */
    eyebrow: string;
    title: string;
  };
  customSection: {
    eyebrow: string;
    title: string;
    body: string;
    /**
     * Highlighted lead-time reminder box.
     */
    note?: string | null;
    cta: string;
    features?:
      | {
          title: string;
          body: string;
          icon?: ('palette' | 'sparkles' | 'truck' | 'message') | null;
          id?: string | null;
        }[]
      | null;
  };
  story: {
    eyebrow: string;
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: string | Media;
    cta?: string | null;
  };
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading and intro above the product grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page".
 */
export interface ShopPage {
  id: string;
  eyebrow: string;
  title: string;
  intro: string;
  /**
   * Shown when the filters return nothing.
   */
  emptyMessage: string;
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  eyebrow: string;
  title: string;
  intro: string;
  image: string | Media;
  howWeWork: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  occasionsColumn: {
    title: string;
    /**
     * On: builds the list from the Occasions collection. Off: uses the custom items below.
     */
    useOccasionsList?: boolean | null;
    items?:
      | {
          term: string;
          definition: string;
          id?: string | null;
        }[]
      | null;
  };
  clientsHeading: string;
  primaryCta: string;
  secondaryCta: string;
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  eyebrow: string;
  title: string;
  intro: string;
  /**
   * The fourth contact card; its value uses the lead time in Settings.
   */
  leadTimeCardLabel: string;
  bulk: {
    title: string;
    body: string;
    primaryCta: string;
    secondaryCta: string;
  };
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pre-order-page".
 */
export interface PreOrderPage {
  id: string;
  eyebrow: string;
  title: string;
  /**
   * {leadTime} is replaced with the lead time from Site Settings.
   */
  intro: string;
  submitLabel: string;
  footnote: string;
  /**
   * Added to the occasion dropdown after the ones from the Occasions collection.
   */
  extraOccasionOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to use the automatic title and description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  announcementBar?: T;
  logo?: T;
  footerNote?: T;
  whatsappNumber?: T;
  phoneDisplay?: T;
  email?: T;
  instagramUrl?: T;
  instagramHandle?: T;
  leadTimeDays?: T;
  boxPriceMin?: T;
  boxPriceMax?: T;
  quoteNote?: T;
  waTemplates?:
    | T
    | {
        general?: T;
        order?: T;
        custom?: T;
        product?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        primaryCta?: T;
        secondaryCta?: T;
        badges?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        priceBadge?:
          | T
          | {
              title?: T;
              sub?: T;
            };
      };
  clientsHeading?: T;
  categoriesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  collectionsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  occasionsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  featuredSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  featuredLimit?: T;
  howToOrderSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  howToOrderSteps?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  instagramSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  instagramImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  instagramCta?: T;
  testimonialsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  customSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        note?: T;
        cta?: T;
        features?:
          | T
          | {
              title?: T;
              body?: T;
              icon?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        cta?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page_select".
 */
export interface ShopPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  intro?: T;
  emptyMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  intro?: T;
  image?: T;
  howWeWork?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  occasionsColumn?:
    | T
    | {
        title?: T;
        useOccasionsList?: T;
        items?:
          | T
          | {
              term?: T;
              definition?: T;
              id?: T;
            };
      };
  clientsHeading?: T;
  primaryCta?: T;
  secondaryCta?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  intro?: T;
  leadTimeCardLabel?: T;
  bulk?:
    | T
    | {
        title?: T;
        body?: T;
        primaryCta?: T;
        secondaryCta?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pre-order-page_select".
 */
export interface PreOrderPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  intro?: T;
  submitLabel?: T;
  footnote?: T;
  extraOccasionOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}